### ISSUE TITLE
Some more error after stoped processing an resuming i got this error  cannot access local variable 'preprocessed_sentences' where it is not associated with a value

### ISSUE THREAD

**Issue by yodatak** [lukaszliniewicz/Pandrator#10]
Your app is realy awsome ( result is realy great we should make it simple to use and with all the api server but annother story)

2024-04-25 02:21:04,244 - DEBUG - http://localhost:8020 "GET /docs HTTP/1.1" 200 939
Exception in thread Thread-5 (start_optimisation):
Traceback (most recent call last):
  File "/usr/lib64/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/var/home/yodatak/Projets/public/Pandrator/pandrator.py", line 1959, in start_optimisation
    for sentence_dict in preprocessed_sentences:
                         ^^^^^^^^^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'preprocessed_sentences' where it is not associated with a value
2024-04-25 02:21:09,848 - DEBUG - Starting new HTTP connection (1): localhost:8020
2024-04-25 02:21:09,849 - DEBUG - http://localhost:8020 "GET /docs HTTP/1.1" 200 939
Exception in thread Thread-6 (start_optimisation):
Traceback (most recent call last):
  File "/usr/lib64/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/var/home/yodatak/Projets/public/Pandrator/pandrator.py", line 1959, in start_optimisation
    for sentence_dict in preprocessed_sentences:
                         ^^^^^^^^^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'preprocessed_sentences' where it is not associated with a value

**Comment by lukaszliniewicz** [comment]
Sorry to hear there is another issue. What file type did you use? I couldn't replicate this:


https://github.com/lukaszliniewicz/Pandrator/assets/75737665/1e93f7c1-d470-429a-a04c-300684d19c11

**Comment by zeta274** [comment]
This is still an issue. It happens after deleting the Generated Sentences, say, if I don't like them and I want to start over. I delete them all, then "Start Generation". Boom: cannot access local variable 'preprocessed_sentences'
