### ISSUE TITLE
archive file with errors and  whisperX for older graphics cards

### ISSUE THREAD

**Issue by jacooooooooool** [lukaszliniewicz/Pandrator#50]
Hello, I'm trying to use your project again, this time the option from your packed archive: Pandrator_XTTS_v025.7z when copying to disk, at some point a "disk read error" appears as if the archive had errors, I tried to download the file several times and always the same :(

I also noticed that in your other project "Easy XTTS trainer" which is part of Pantrator, you recommend creating 2 separate Conda environments for xtts_training and whisperx, which is understandable because they have different dependencies.

Could you help me install the older whisperX "inside" your project that works with older graphics cards? (1080Ti 11Gb)  because it is whisperX that causes problems when trying to train.
I know that you suggested cheap computing platforms for testing earlier, but I think my card still has a lot to offer :)

It would also be nice if there was a script in the Pandrator folder "cmd_windows.bat" which starts the conda environment for whisperX to be able to fix some errors that pop up with older graphics cards, here is an example of such a script:

====================

@echo off

cd /D "%~dp0"

echo "%CD%"| findstr /C:" " >nul && echo This script relies on Miniconda which can not be silently installed under a path with spaces. && goto end

set PATH=%PATH%;%SystemRoot%\system32

@rem config
set CONDA_ROOT_PREFIX=%cd%\Pandrator\conda
set INSTALL_ENV_DIR=%cd%\Pandrator\env

@rem activate installer env
call "%CONDA_ROOT_PREFIX%\condabin\conda.bat" activate "%INSTALL_ENV_DIR%" || ( echo. && echo Miniconda hook not found. && goto end )

@rem enter commands
cmd /k "%*"

:end
pause

======================

I also wanted to thank you for a fantastic project that has a very simple installer

is there a chance that the launcher will have an option that changes some default whisperx settings ( --fp16 FP16 ) by default it is TRUE to FALSE or editing this function

**Comment by lukaszliniewicz** [comment]
Sure, I will try to find a way to make this work. Thanks for finding out what the problem was.

**Comment by jacooooooooool** [comment]
I have already installed everything using the installer everything works for me except Train XTTS because:

ValueError: Requested float16 compute type, but the target device or backend does not support efficient float16 computation.

that's why the option that changes the default whisperx settings ( --fp16 FP16 ) is TRUE by default, changing it to FALSE or --fp8 should force it to work on older nvidia systems

**Comment by lukaszliniewicz** [comment]
Please try updating Pandrator from the installer and check if it works now.

**Comment by jacooooooooool** [comment]
I'm wondering about this error in the log: 
Error running WhisperX with environment whisperx_installer: Command '['..\\conda\\Scripts\\conda.exe', 'run', '-n', 'whisperx_installer', 'python', '-m', 'whisperx', 'C:\\Users\\Jacek\\Downloads\\Pandrator\\easy_xtts_trainer\\man\\audio_sources\\man.wav', '--language', 'pl', '--model', 'large-v3', '--output_dir', 'C:\\Users\\Jacek\\Downloads\\Pandrator\\easy_xtts_trainer\\man\\transcriptions', '--output_format', 'json']' returned non-zero exit status 1.


it will delete the entire installation and reinstall it after restarting the computer

**Comment by lukaszliniewicz** [comment]
Please wait a moment, I will give you a new .exe.

**Comment by jacooooooooool** [comment]
ok fantastic, thank you for such a quick response :)

**Comment by lukaszliniewicz** [comment]
Please try this one: https://1drv.ms/u/s!AgSiDu9lV3iMnoVr1Pbdti5xo10P4A?e=uCs1GB.

**Comment by jacooooooooool** [comment]
unfortunately after reinstallation there is a similar error which suggests that whisperX will not work with --ft16 enabled, here is the whole log:

2024-10-15 21:52:37,854 [INFO] XTTS Training: ERROR conda.cli.main_run:execute(125): `conda run python easy_xtts_trainer.py --session Don --whisper-model large-v3 --source-language pl --epochs 6 --gradient 1 --batch 2 --sample-method mixed -i C:/Users/Jacek/Music/Donald/Don` failed. (See above for error)
2024-10-15 21:52:37,855 [INFO] XTTS Training: Error running WhisperX with environment whisperx_installer: Command '['..\\conda\\Scripts\\conda.exe', 'run', '-n', 'whisperx_installer', 'python', '-m', 'whisperx', 'C:\\Users\\Jacek\\Downloads\\Pandrator\\easy_xtts_trainer\\Don\\audio_sources\\don1.wav', '--language', 'pl', '--model', 'large-v3', '--output_dir', 'C:\\Users\\Jacek\\Downloads\\Pandrator\\easy_xtts_trainer\\Don\\transcriptions', '--output_format', 'json', '--fp16', 'False']' returned non-zero exit status 1.
2024-10-15 21:52:37,855 [INFO] XTTS Training: Standard output:
2024-10-15 21:52:37,855 [INFO] XTTS Training: Standard error: c:\Users\Jacek\Downloads\Pandrator\conda\envs\whisperx_installer\lib\inspect.py:869: UserWarning: Module 'speechbrain.pretrained' was deprecated, redirecting to 'speechbrain.inference'. Please update your script. This is a change from SpeechBrain 1.0. See: https://github.com/speechbrain/speechbrain/releases/tag/v1.0.0
2024-10-15 21:52:37,855 [INFO] XTTS Training: if ismodule(module) and hasattr(module, '__file__'):
2024-10-15 21:52:37,855 [INFO] XTTS Training: c:\Users\Jacek\Downloads\Pandrator\conda\envs\whisperx_installer\lib\site-packages\pyannote\audio\pipelines\speaker_verification.py:45: UserWarning: Module 'speechbrain.pretrained' was deprecated, redirecting to 'speechbrain.inference'. Please update your script. This is a change from SpeechBrain 1.0. See: https://github.com/speechbrain/speechbrain/releases/tag/v1.0.0
2024-10-15 21:52:37,855 [INFO] XTTS Training: from speechbrain.pretrained import (
2024-10-15 21:52:37,856 [INFO] XTTS Training: Traceback (most recent call last):
2024-10-15 21:52:37,856 [INFO] XTTS Training: File "c:\Users\Jacek\Downloads\Pandrator\conda\envs\whisperx_installer\lib\runpy.py", line 196, in _run_module_as_main
2024-10-15 21:52:37,856 [INFO] XTTS Training: return _run_code(code, main_globals, None,
2024-10-15 21:52:37,856 [INFO] XTTS Training: File "c:\Users\Jacek\Downloads\Pandrator\conda\envs\whisperx_installer\lib\runpy.py", line 86, in _run_code
2024-10-15 21:52:37,856 [INFO] XTTS Training: exec(code, run_globals)
2024-10-15 21:52:37,856 [INFO] XTTS Training: File "c:\Users\Jacek\Downloads\Pandrator\conda\envs\whisperx_installer\lib\site-packages\whisperx\__main__.py", line 4, in <module>
2024-10-15 21:52:37,856 [INFO] XTTS Training: cli()
2024-10-15 21:52:37,857 [INFO] XTTS Training: File "c:\Users\Jacek\Downloads\Pandrator\conda\envs\whisperx_installer\lib\site-packages\whisperx\transcribe.py", line 170, in cli
2024-10-15 21:52:37,857 [INFO] XTTS Training: model = load_model(model_name, device=device, device_index=device_index, download_root=model_dir, compute_type=compute_type, language=args['language'], asr_options=asr_options, vad_options={"vad_onset": vad_onset, "vad_offset": vad_offset}, task=task, threads=faster_whisper_threads)
2024-10-15 21:52:37,857 [INFO] XTTS Training: File "c:\Users\Jacek\Downloads\Pandrator\conda\envs\whisperx_installer\lib\site-packages\whisperx\asr.py", line 288, in load_model
2024-10-15 21:52:37,857 [INFO] XTTS Training: model = model or WhisperModel(whisper_arch,
2024-10-15 21:52:37,857 [INFO] XTTS Training: File "c:\Users\Jacek\Downloads\Pandrator\conda\envs\whisperx_installer\lib\site-packages\faster_whisper\transcribe.py", line 133, in __init__
2024-10-15 21:52:37,857 [INFO] XTTS Training: self.model = ctranslate2.models.Whisper(
2024-10-15 21:52:37,857 [INFO] XTTS Training: ValueError: Requested float16 compute type, but the target device or backend do not support efficient float16 computation.
2024-10-15 21:52:37,857 [INFO] XTTS Training: 
2024-10-15 21:52:37,858 [INFO] XTTS Training: ERROR conda.cli.main_run:execute(125): `conda run python -m whisperx C:\Users\Jacek\Downloads\Pandrator\easy_xtts_trainer\Don\audio_sources\don1.wav --language pl --model large-v3 --output_dir C:\Users\Jacek\Downloads\Pandrator\easy_xtts_trainer\Don\transcriptions --output_format json --fp16 False` failed. (See above for error)
2024-10-15 21:52:37,858 [INFO] XTTS Training: 
2024-10-15 21:52:37,858 [INFO] XTTS Training: An unexpected error occurred: name 'possible_paths' is not defined
2024-10-15 21:52:37,858 [INFO] XTTS Training:

**Comment by lukaszliniewicz** [comment]
Hmm, it seems that the argument was set correctly: 

2024-10-15 21:52:37,858 [INFO] XTTS Training: ERROR conda.cli.main_run:execute(125): conda run python -m whisperx C:\Users\Jacek\Downloads\Pandrator\easy_xtts_trainer\Don\audio_sources\don1.wav --language pl --model large-v3 --output_dir C:\Users\Jacek\Downloads\Pandrator\easy_xtts_trainer\Don\transcriptions --output_format json --fp16 False failed. (See above for error)

Maybe we have to set it to int8 explicitly. I will make another change.

**Comment by lukaszliniewicz** [comment]
Please update Pandrator and try again. A new installation should not be necessary.

**Comment by jacooooooooool** [comment]
OK

**Comment by jacooooooooool** [comment]
> Hmm, wygląda na to, że argument został ustawiony poprawnie:
> 
> 2024-10-15 21:52:37,858 [INFO] Szkolenie XTTS: BŁĄD conda.cli.main_run:execute(125): conda run python -m whisperx C:\Users\Jacek\Downloads\Pandrator\easy_xtts_trainer\Don\audio_sources\don1.wav --language pl --model large-v3 --output_dir C:\Users\Jacek\Downloads\Pandrator\easy_xtts_trainer\Don\transcriptions --output_format json **--fp16 False** nie powiodło się. (Zobacz powyżej błąd)
> 
> Może musimy ustawić to jawnie na int8. Wprowadzę inną zmianę.

moim zdaniem

> Hmm, it seems that the argument was set correctly:
> 
> 2024-10-15 21:52:37,858 [INFO] XTTS Training: ERROR conda.cli.main_run:execute(125): conda run python -m whisperx C:\Users\Jacek\Downloads\Pandrator\easy_xtts_trainer\Don\audio_sources\don1.wav --language pl --model large-v3 --output_dir C:\Users\Jacek\Downloads\Pandrator\easy_xtts_trainer\Don\transcriptions --output_format json **--fp16 False** failed. (See above for error)
> 
> Maybe we have to set it to int8 explicitly. I will make another change.


in my opinion this is the best solution for my old graphics card

**Comment by jacooooooooool** [comment]
there is an improvement after the update The training is working, I am waiting for its end to confirm that the corrections made have brought the effect
