### ISSUE TITLE
Can no longer use .DOCX as source file

### ISSUE THREAD

**Issue by Snoddas76** [lukaszliniewicz/Pandrator#66]
Hi!

I have an issue after a new install of Pandrator. I have used .DOCX files as source without issues. Then, after Conda server stopped working, I reinstalled Pandrator and suddenly I can no longer use .DOCX files as source file. When I load the .DOCX file, it looks fine in the GUI but in the Conda command window I get this error:

Exception in Tkinter callback
Traceback (most recent call last):
  File "D:\TTS\Pandrator\conda\envs\pandrator_installer\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "D:\TTS\Pandrator\conda\envs\pandrator_installer\lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
    self._command()
  File "D:\TTS\Pandrator\Pandrator\pandrator.py", line 2711, in select_file
    if run_ebook_convert(["ebook-convert", self.pre_selected_source_file, txt_path]):
  File "D:\TTS\Pandrator\Pandrator\pandrator.py", line 2705, in run_ebook_convert
    subprocess.run(command, check=True)
  File "D:\TTS\Pandrator\conda\envs\pandrator_installer\lib\subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "D:\TTS\Pandrator\conda\envs\pandrator_installer\lib\subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "D:\TTS\Pandrator\conda\envs\pandrator_installer\lib\subprocess.py", line 1456, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

Other file types work, but they don't generate the text correctly so I really want to use .DOCX.

Any help would be appreciated, thanks.

**Comment by lukaszliniewicz** [comment]
Please check if you have Calibre installed.

**Comment by Snoddas76** [comment]
Thanks for the tip. When I had Predator install Calibre, as when I reinstalled Predator, the issue remained. I now tried uninstalling Calibre and manually installing the newest version, and that solved the issue. Thank you :)
