### ISSUE TITLE
If Chocolatey is so great... error, error, error from a fresh install...again.

### ISSUE THREAD

**Issue by sasori7** [lukaszliniewicz/Pandrator#67]
Installed:
 - chocolatey-dotnetfx.extension v1.0.1
 - chocolatey-visualstudio.extension v1.11.1
 - dotnetfx v4.8.0.20220524
 - KB2919355 v1.0.20160915
 - KB2919442 v1.0.20160915
 - visualstudio2022buildtools v117.12.0
 - visualstudio-installer v2.0.3

Packages requiring reboot:
 - visualstudio2022buildtools (exit code 3010)

The recent package changes indicate a reboot is necessary.
 Please reboot at your earliest convenience.

2024-11-20 17:42:06,437 - ERROR - Failed to install visualstudio2022buildtools using Chocolatey.
2024-11-20 17:42:06,439 - INFO - Error during Build Tools installation. Check the log for details.
2024-11-20 17:42:06,446 - INFO - Cloning repositories...
2024-11-20 17:42:06,446 - INFO - Cloning repository https://github.com/daswer123/xtts-api-server.git to D:\Pandrator_XTTS_v030\Pandrator\xtts-api-server...
2024-11-20 17:42:06,448 - ERROR - Failed to clone repository: [WinError 183] Cannot create a file when that file already exists: 'D:\\Pandrator_XTTS_v030\\Pandrator\\xtts-api-server\\.git'
2024-11-20 17:42:06,448 - ERROR - Installation failed: [WinError 183] Cannot create a file when that file already exists: 'D:\\Pandrator_XTTS_v030\\Pandrator\\xtts-api-server\\.git'
2024-11-20 17:42:06,448 - ERROR - Traceback (most recent call last):
  File "pandrator_installer_launcher.py", line 1093, in install_process
  File "pandrator_installer_launcher.py", line 987, in clone_repo
  File "dulwich\porcelain.py", line 584, in clone
  File "dulwich\client.py", line 801, in clone
  File "dulwich\repo.py", line 1735, in init
FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'D:\\Pandrator_XTTS_v030\\Pandrator\\xtts-api-server\\.git'

2024-11-20 17:42:06,448 - INFO - Installation failed. Check the log for details.

**Comment by lukaszliniewicz** [comment]
I've taken the Build Tools from the main workflow, they can be installed separately now. Hope this solves it.
